name: set_theory
description: A comprehensive implementation of Set Theory operations in Dart
version: 1.0.0
repository: https://github.com/da578/set_theory

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
